In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [2]:
df = pd.read_csv("data/nlp-230518-121949.csv")
df.head()

Unnamed: 0                                               Text
0           0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...
1           1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...
2           2  Öncelikle yapay zekanın ne olduğunu, #dijitala...
3           3  9. Baidu Research: Çin'in önde gelen arama mot...
4           4  4. Microsoft AI: Microsoft'un yapay zeka tekno...

In [3]:
import on_islem
df['Text2'] = df['Text'].apply(on_islem.pre_processing)
df['Text2'] = df['Text2'].apply(on_islem.remove_space)
df.head()

Unnamed: 0                                               Text   
0           0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1           1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2           2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3           3  9. Baidu Research: Çin'in önde gelen arama mot...   
4           4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                               Text2  
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [4]:
#Boş liste kontrolü
df[df["Text2"].str[0].isnull()]

Unnamed: 0                                               Text Text2
194         194  #hesaplamalısosyalbilimler #computationalsocia...    []
464         464  #investment #software #technology #tech #innov...    []
544         544  @barolar #ImageRecognition #SınırlıHafıza #Lim...    []

In [5]:
df_index = df[df["Text2"].str[0].isnull()].index
df = df.drop(df_index)
df = df.reset_index()
del df["index"]

df[df["Text2"].str[0].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, Text, Text2]
Index: []

In [6]:
df["Text2"]

0      [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...
1      [veri, analiz, edin, chatgptyi, kullanarak, do...
2      [öncelik, yapay, zeka, olduğunu, iç, önemli, o...
3      [baidu, research, çin, ön, gele, ara, motor, b...
4      [microsoft, ai, microsoft, yapay, zeka, teknol...
                             ...                        
850    [doğal, dil, işle, alan, yük, lisansdoktor, ya...
851                                   [dogal, dil, isle]
852       [ver, madencilik, doğal, dil, işle, uygulamas]
853    [doğal, dil, işleme, il, ilgil, deney, ola, ya...
854    [hafta, öğrencilik, hayat, kaldık, yer, deva, ...
Name: Text2, Length: 855, dtype: object

In [7]:
df["Text3"] = [' '.join(item) for item in df["Text2"]]
df

Unnamed: 0                                               Text   
0             0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1             1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2             2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3             3  9. Baidu Research: Çin'in önde gelen arama mot...   
4             4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..          ...                                                ...   
850         853  doğal dil işleme alanında yüksek lisans-doktor...   
851         854                           dogal dil isleme şeyleri   
852         855  Bir veri madenciliği ve doğal dil işleme uygul...   
853         856  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854         857  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                 Text2   
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                 Text3  
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...  
1    veri analiz edin chatgptyi kullanarak doğal di...  
2    öncelik yapay zeka olduğunu iç önemli olduk kı...  
3    baidu research çin ön gele ara motor baidun ar...  
4    microsoft ai microsoft yapay zeka teknoloji od...  
..                                                 ...  
850  doğal dil işle alan yük lisansdoktor yapa danı...  
851                                     dogal dil isle  
852            ver madencilik doğal dil işle uygulamas  
853  doğal dil işleme il ilgil deney ola yazılımcı ...  
854  hafta öğrencilik hayat kaldık yer deva ediyoru...  

[855 rows x 4 columns]

In [8]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df["Text3"].tolist())
X

<855x4786 sparse matrix of type '<class 'numpy.int64'>'
	with 16937 stored elements in Compressed Sparse Row format>

In [9]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
df["Text4"] = X.toarray().tolist()
df.head()

Unnamed: 0                                               Text   
0           0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1           1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2           2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3           3  9. Baidu Research: Çin'in önde gelen arama mot...   
4           4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                               Text2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                               Text3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                               Text4  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["Text3"].tolist())
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [12]:
set(X.toarray()[0])

{0.0,
 0.03508115658001388,
 0.03685011328026531,
 0.12317029281566404,
 0.1287180325367376,
 0.1293951901484212,
 0.14937145922687903,
 0.15331933006757356,
 0.15474585010773745,
 0.15623579147571884,
 0.1669097751456677,
 0.17386946496025046,
 0.1765523493830673,
 0.19014279446116142,
 0.19978536869856103,
 0.20581084119178317,
 0.21337581377665515,
 0.22232665378265135,
 0.22301838801405474,
 0.2366088330921489,
 0.3162294875300779}

In [13]:
df["Text5"] = X.toarray().tolist()
df

Unnamed: 0                                               Text   
0             0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1             1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2             2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3             3  9. Baidu Research: Çin'in önde gelen arama mot...   
4             4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..          ...                                                ...   
850         853  doğal dil işleme alanında yüksek lisans-doktor...   
851         854                           dogal dil isleme şeyleri   
852         855  Bir veri madenciliği ve doğal dil işleme uygul...   
853         856  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854         857  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                 Text2   
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                 Text3   
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka olduğunu iç önemli olduk kı...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
850  doğal dil işle alan yük lisansdoktor yapa danı...   
851                                     dogal dil isle   
852            ver madencilik doğal dil işle uygulamas   
853  doğal dil işleme il ilgil deney ola yazılımcı ...   
854  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                 Text4   
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
850  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                 Text5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
850  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[855 rows x 6 columns]

In [14]:
from gensim.models import Word2Vec

In [15]:
df.head()

Unnamed: 0                                               Text   
0           0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1           1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2           2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3           3  9. Baidu Research: Çin'in önde gelen arama mot...   
4           4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                               Text2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                               Text3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                               Text4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                               Text5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [16]:
model = Word2Vec(sentences=df["Text2"].tolist(), vector_size=100, window = 5, min_count=1)
model.save("data/word2vec.model")

In [17]:
print(model)

Word2Vec<vocab=4797, vector_size=100, alpha=0.025>


In [18]:
words = list(model.wv.index_to_key)
words[0:6]

['dil', 'doğal', 'işle', 'yapay', 'zeka', 'il']

In [19]:
model.wv.key_to_index["yapay"]

3

In [20]:
model.wv[3]

array([-0.05955906,  0.17044228,  0.06583256, -0.05457689,  0.07966211,
       -0.26772624,  0.07097063,  0.42765158, -0.19495244, -0.11641115,
       -0.08431507, -0.25817877, -0.01067137,  0.099158  ,  0.02456297,
       -0.14520936,  0.06557029, -0.16169849, -0.04482417, -0.40143672,
        0.14043377, -0.00046503,  0.18824424, -0.06309168, -0.00855854,
       -0.0064832 , -0.05148574, -0.0275775 , -0.11395451,  0.03354884,
        0.22009414, -0.04289003,  0.05388521, -0.24383558, -0.08871925,
        0.23909724,  0.07358439, -0.2304823 , -0.08577948, -0.2589067 ,
        0.06692643, -0.19692606, -0.02707584, -0.04874843,  0.15561731,
       -0.07519434, -0.19436522, -0.05671222,  0.11422723,  0.11152676,
        0.12621254, -0.14534819, -0.10551284,  0.0110133 , -0.12363514,
        0.04699861,  0.1170463 , -0.07621146, -0.0979741 ,  0.04846471,
        0.04025116, -0.00252775,  0.02597068,  0.04429524, -0.17367592,
        0.22490668,  0.0531531 ,  0.12264193, -0.20591862,  0.19

In [21]:
model.wv.get_vector("yapay")

array([-0.05955906,  0.17044228,  0.06583256, -0.05457689,  0.07966211,
       -0.26772624,  0.07097063,  0.42765158, -0.19495244, -0.11641115,
       -0.08431507, -0.25817877, -0.01067137,  0.099158  ,  0.02456297,
       -0.14520936,  0.06557029, -0.16169849, -0.04482417, -0.40143672,
        0.14043377, -0.00046503,  0.18824424, -0.06309168, -0.00855854,
       -0.0064832 , -0.05148574, -0.0275775 , -0.11395451,  0.03354884,
        0.22009414, -0.04289003,  0.05388521, -0.24383558, -0.08871925,
        0.23909724,  0.07358439, -0.2304823 , -0.08577948, -0.2589067 ,
        0.06692643, -0.19692606, -0.02707584, -0.04874843,  0.15561731,
       -0.07519434, -0.19436522, -0.05671222,  0.11422723,  0.11152676,
        0.12621254, -0.14534819, -0.10551284,  0.0110133 , -0.12363514,
        0.04699861,  0.1170463 , -0.07621146, -0.0979741 ,  0.04846471,
        0.04025116, -0.00252775,  0.02597068,  0.04429524, -0.17367592,
        0.22490668,  0.0531531 ,  0.12264193, -0.20591862,  0.19

In [22]:
def word2vec(value):
    model = Word2Vec.load("data/word2vec.model")
    bfr_list = []
    bfr_len = len(value)

    for k in value:
        bfr = model.wv.key_to_index[k]
        bfr = model.wv[bfr]
        bfr_list.append(bfr)
    
    bfr_list = sum(bfr_list)
    bfr_list = bfr_list/bfr_len
    return bfr_list.tolist()

In [23]:
df.head()

Unnamed: 0                                               Text   
0           0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1           1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2           2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3           3  9. Baidu Research: Çin'in önde gelen arama mot...   
4           4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                               Text2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                               Text3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                               Text4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                               Text5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [24]:
df["Text6"] = df["Text2"].apply(word2vec)
df.head()

Unnamed: 0                                               Text   
0           0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1           1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2           2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3           3  9. Baidu Research: Çin'in önde gelen arama mot...   
4           4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                               Text2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                               Text3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                               Text4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                               Text5   
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  \
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                               Text6  
0  [-0.02718597650527954, 0.07769615948200226, 0....  
1  [-0.020110124722123146, 0.06124737486243248, 0...  
2  [-0.023166516795754433, 0.07455279678106308, 0...  
3  [-0.021847764030098915, 0.06907889991998672, 0...  
4  [-0.03098914958536625, 0.09604530036449432, 0....

In [26]:
df["bow"] = on_islem.bag_of_words(df["Text3"])
df["tfidf"] = on_islem.tf_idf(df["Text3"])
df["word2vec"] = df["Text2"].apply(on_islem.word2vec)

In [27]:
df.head()

Unnamed: 0                                               Text   
0           0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1           1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2           2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3           3  9. Baidu Research: Çin'in önde gelen arama mot...   
4           4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                               Text2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                               Text3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                               Text4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                               Text5   
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  \
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                               Text6   
0  [-0.02718597650527954, 0.07769615948200226, 0....  \
1  [-0.020110124722123146, 0.06124737486243248, 0...   
2  [-0.023166516795754433, 0.07455279678106308, 0...   
3  [-0.021847764030098915, 0.06907889991998672, 0...   
4  [-0.03098914958536625, 0.09604530036449432, 0....   

                                                 bow   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                               tfidf   
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  \
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                            word2vec  
0  [-0.02718597650527954, 0.07769615948200226, 0....  
1  [-0.020110124722123146, 0.06124737486243248, 0...  
2  [-0.023166516795754433, 0.07455279678106308, 0...  
3  [-0.021847764030098915, 0.06907889991998672, 0...  
4  [-0.03098914958536625, 0.09604530036449432, 0....